<a href="https://colab.research.google.com/github/rajagopal17/Text-Analysis-with-Spacy/blob/master/Text_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##https://www.kaggle.com/zackakil/done-nlp-using-word-vectors-with-spacy-cldspn

##https://www.oreilly.com/library/view/applied-text-analysis/9781491963036/ch04.html

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rc('font', size=14)
sns.set(style='white')
sns.set(style='whitegrid', color_codes=True)
import csv
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import train_test_split


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from __future__ import unicode_literals
import spacy
from spacy.tokens import doc
from spacy.matcher import Matcher 
from spacy.tokens import Span
from spacy import displacy
print (spacy.__version__)
import spacy.cli
spacy.cli.download("en_core_web_lg")
nlp=spacy.load('en_core_web_lg')
from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English
parser = English()
import string
punctuations=string.punctuation

2.2.4
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')


##Download Large model for Spacy

In [ ]:
#!python -m spacy download en_core_web_lg
################################################
#import spacy.cli
#spacy.cli.download("en_core_web_lg")

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_lg')


In [ ]:
import nltk
import string
nltk.download('punkt')

def tokenize(text):
    stem = nltk.stem.SnowballStemmer('english')
    text = text.lower()

    for token in nltk.word_tokenize(text):
        if token in string.punctuation: continue
        yield stem.stem(token)

corpus = [
    "The elephant sneezed at the sight of potatoes.",
    "Bats can see via echolocation. See the bat sight sneeze!",
    "Wondering, she opened the door to the studio.",
]

from collections import defaultdict

def vectorize(doc):
    features = defaultdict(int)
    for token in tokenize(doc):
        features[token] += 1
        print(features)




[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
vectors = map(vectorize, corpus)
list(vectors)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectors = vectorizer.fit(corpus)
print(vectorizer.vocabulary_)

{'the': 16, 'elephant': 6, 'sneezed': 14, 'at': 0, 'sight': 12, 'of': 7, 'potatoes': 9, 'bats': 2, 'can': 3, 'see': 10, 'via': 18, 'echolocation': 5, 'bat': 1, 'sneeze': 13, 'wondering': 19, 'she': 11, 'opened': 8, 'door': 4, 'to': 17, 'studio': 15}


In [ ]:
# If we would like to actually create a vector, we can do so by passing the
# text into the vectorizer to get back counts
vector = vectorizer.transform(corpus)
print(vector.toarray())
                              

[[1 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 2 0 0 0]
 [0 1 1 1 0 1 0 0 0 0 2 0 1 1 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 2 1 0 1]]


In [ ]:
vectorizer.transform(['elephant']).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
print(vectorizer.fit_transform(corpus).toarray())

[[1 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 2 0 0 0]
 [0 1 1 1 0 1 0 0 0 0 2 0 1 1 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 2 1 0 1]]


In [ ]:
print(vectorizer.vocabulary_)

{'the': 16, 'elephant': 6, 'sneezed': 14, 'at': 0, 'sight': 12, 'of': 7, 'potatoes': 9, 'bats': 2, 'can': 3, 'see': 10, 'via': 18, 'echolocation': 5, 'bat': 1, 'sneeze': 13, 'wondering': 19, 'she': 11, 'opened': 8, 'door': 4, 'to': 17, 'studio': 15}


In [ ]:

doc=nlp(str(corpus))
for token in doc:
  print(token)


In [ ]:
from scipy.spatial.distance import cosine
nlp('doctor').similarity(nlp('medical'))

0.7008181125452967

In [ ]:
nlp('elephant').vector

In [ ]:
for word in doc:
    print(word, nlp('hear').similarity(word))

In [ ]:
nlp('what ever you want to say').vector.sum()

1.024536